export const PRODUCTS = [
  // ==================== EJECUTIVAS ====================
  {
    id: 1,
    name: "Caja Festiva",
    slug: "caja-festiva",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-caja-festiva-2.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-caja-festiva-2.png",
  },
  {
    id: 2,
    name: "Caja Festiva Clásica",
    slug: "caja-festiva-clasica",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-caja-festiva-clasica.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-caja-festiva-clasica.png",
  },
  {
    id: 3,
    name: "Caja Festiva Stracon",
    slug: "caja-festiva-stracon",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-caja-festiva-stracon.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-caja-festiva-stracon.png",
  },
  {
    id: 4,
    name: "Caja Tradición",
    slug: "caja-tradicion",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-caja-tradicion.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-caja-tradicion.png",
  },
  {
    id: 5,
    name: "Cesto Organizador Essential",
    slug: "cesto-organizador-essential",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-cesto-organizador-essential.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-cesto-organizador-essential.png",
  },
  {
    id: 6,
    name: "Contenedor Premium",
    slug: "contenedor-premium",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-contenedor-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-contenedor-premium.png",
  },
  {
    id: 7,
    name: "Cooler Premium",
    slug: "cooler-premium",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-cooler-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-cooler-premium.png",
  },
  {
    id: 8,
    name: "Backpack Pro",
    slug: "backpack-pro",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-backpack-pro.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-backpack-pro.png",
  },
  {
    id: 9,
    name: "Bolso Cooler Premium",
    slug: "bolso-cooler-premium",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-bolso-cooler-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-bolso-cooler-premium.png",
  },
  {
    id: 10,
    name: "Bolso Térmico Deluxe",
    slug: "bolso-termico-deluxe",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-bolso-termico-deluxe.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-bolso-termico-deluxe.png",
  },
  {
    id: 11,
    name: "Carry On Elite",
    slug: "carry-on-elite",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-carry-on-elite.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-carry-on-elite.png",
  },
  {
    id: 12,
    name: "Cooler Trolley Premium",
    slug: "cooler-trolley-premium",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-cooler-trolley-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-cooler-trolley-premium.png",
  },
  {
    id: 13,
    name: "Corporativa Premium",
    slug: "corporativa-premium",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-corporativa-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-corporativa-premium.png",
  },
  {
    id: 14,
    name: "Executive Tote",
    slug: "executive-tote",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-executive-tote.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-executive-tote.png",
  },
  {
    id: 15,
    name: "Maletín Premium",
    slug: "maletin-premium",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-maletin-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-maletin-premium.png",
  },
  {
    id: 16,
    name: "Mochila Laptop",
    slug: "mochila-laptop",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-mochila-laptop.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-mochila-laptop.png",
  },
  {
    id: 17,
    name: "Signature",
    slug: "signature",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-signature.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-signature.png",
  },
  {
    id: 18,
    name: "Travel Premium",
    slug: "travel-premium",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-travel-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-travel-premium.png",
  },
  {
    id: 19,
    name: "Trolley Deluxe",
    slug: "trolley-deluxe",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-trolley-deluxe.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-trolley-deluxe.png",
  },
  {
    id: 20,
    name: "Urban Backpack",
    slug: "urban-backpack",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-urban-backpack.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-urban-backpack.png",
  },
  {
    id: 21,
    name: "Voyager Premium",
    slug: "voyager-premium",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-voyager-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-ejecutiva-voyager-premium.png",
  },
  {
    id: 22,
    name: "Mochila Tecsup",
    slug: "mochila-tecsup",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-mochila-ejecutiva-tecsup.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-mochila-ejecutiva-tecsup.png",
  },
  {
    id: 23,
    name: "Mochila Urban Style",
    slug: "mochila-urban-style",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-mochila-urban-style.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-mochila-urban-style.png",
  },
  {
    id: 24,
    name: "Nutritiva Gourmet",
    slug: "nutritiva-gourmet",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña corporativa. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-nutritiva-gourmet.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-nutritiva-gourmet.png",
  },

  // ==================== EXCLUSIVAS ====================
  {
    id: 6,
    name: "Cooler Trolley Premium",
    slug: "cooler-trolley-premium-exclusiva",
    price: 0,
    category: "exclusivas",
    featured: false,
    description: "Canasta navideña exclusiva. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-cooler-trolley-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-cooler-trolley-premium.png",
  },
  {
    id: 7,
    name: "Cooler Trolley VIP",
    slug: "cooler-trolley-vip",
    price: 0,
    category: "exclusivas",
    featured: false,
    description: "Canasta navideña exclusiva. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-cooler-trolley-vip.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/canasta-navidena-cooler-trolley-vip.png",
  },

  // ==================== FAMILIARES ====================
  {
    id: 11,
    name: "Canastas textiles",
    slug: "canastas-textiles",
    price: 0,
    category: "familiares",
    featured: true,
    description: "Canastas tejidas en telas y fibras naturales, ideales para regalos corporativos.",
    contents: [],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-4.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-4.jpg",
  },
  {
    id: 12,
    name: "Canastas de plástico",
    slug: "canastas-de-plastico",
    price: 0,
    category: "familiares",
    featured: true,
    description: "Canastas resistentes y versátiles fabricadas en plástico de alta calidad.",
    contents: [],
    image: "https://publiventa.pe/wp-content/uploads/2017/10/canasta10.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2017/10/canasta10.jpg",
  },

  // ==================== CORPORATIVAS ====================
  {
    id: 13,
    name: "Canasta Navideña Tinkuy",
    slug: "canasta-navidena-tinkuy",
    price: 0,
    category: "corporativas",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["D'onofrio panetón caja 880g", "Gloria mantequilla 180g", "Florida filete atún 140g", "Gelatina universal 160g", "Mazamorra universal 150g", "Gloria leche rec. entera 390g", "Compass mermelada fresa 310g", "Pomarola salsa clásica 145g", "Avena premium 3 ositos 900g", "Caja filtrante Mc Collins 100u", "Winter cocoa doypack 150g", "Mayonesa Alacena 190g", "Nestlé leche condensada 393g", "Pallar 500g", "Chocman sixpack"],
    image: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas2.png",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas2.png",
  },
  {
    id: 14,
    name: "Canasta Navideña Wasiykuy",
    slug: "canasta-navidena-wasiykuy",
    price: 0,
    category: "corporativas",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["D'onofrio panetón caja 880g", "Espumante Riccadonna Asti 750ml", "Gloria leche rec. entera 390g", "Chocolate a la taza con azúcar 46% cacao 100g", "Bolsa feliz Navidad galleta Colombina 220g", "Puré de manzana y mango", "Pasta ensalada tornillo 235g", "Toffees surtidos 100g", "Duraznos mitades 820g", "Aceite de oliva virgen 200ml", "Costeño superior 750g", "Azúcar rubia 1 kg", "Mermelada de arándano con mango", "Dip con palta", "Estuche de barquillos Antiu Xixona 75g"],
    image: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas12.png",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas12.png",
  },
  {
    id: 15,
    name: "Canasta Navideña Sullpayki",
    slug: "canasta-navidena-sullpayki",
    price: 0,
    category: "corporativas",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["Panetón 900g caja personalizada", "Aceite vegetal SAO 900ml", "HR familiar 750g", "Sta. Catalina avena 500g", "Arica duraznos 820g", "Marco Polo spaghetti 450g", "Arveja verde Kimolin 500g", "Fanny mermelada pote 320g", "Gelatina Doña Gumi fresa 150g", "Lenteja Komilon 500g", "Azúcar Doña Gumi rubia 500g", "Tableta chocolate Cusco Andino 80g", "Gloria beb durazno 1L", "Gloria leche rec. entera 390g", "Atún trozos aceite Compass 170g", "Toffes Oet surtido 100g"],
    image: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas9.png",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas9.png",
  },

  // ==================== REGALOS NAVIDENOS ====================
  {
    id: 20,
    name: "Brindis Premium",
    slug: "brindis-premium",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-brindis-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-brindis-premium.png",
  },
  {
    id: 21,
    name: "Brindis Premium 2",
    slug: "brindis-premium-2",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-brindis-premium-2.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-brindis-premium-2.png",
  },
  {
    id: 22,
    name: "Executive Box",
    slug: "executive-box",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-executive-box.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-executive-box.png",
  },
  {
    id: 23,
    name: "Gourmet Premium",
    slug: "gourmet-premium",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-gourmet-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-gourmet-premium.png",
  },
  {
    id: 24,
    name: "Taza Gourmet",
    slug: "taza-gourmet",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-taza-gourmet.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-taza-gourmet.png",
  },
  {
    id: 25,
    name: "Taza Premium",
    slug: "taza-premium",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-taza-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-taza-premium.png",
  },
  {
    id: 26,
    name: "Vino Premium",
    slug: "vino-premium",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-vino-premium.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-vino-premium.png",
  },
  {
    id: 27,
    name: "Vino Reserva",
    slug: "vino-reserva",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-vino-reserva.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-vino-reserva.png",
  },
  {
    id: 28,
    name: "Panetón Clásico",
    slug: "paneton-clasico",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-paneton-clasico.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-paneton-clasico.png",
  },
  {
    id: 29,
    name: "Eco Bag",
    slug: "eco-bag",
    price: 0,
    category: "regalos-navidenos",
    featured: false,
    description: "Regalo navideño premium. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-eco-bag.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-eco-bag.png",
  },

  // ==================== CESTAS GOURMET ====================
  {
    id: 16,
    name: "BBQ Gourmet",
    slug: "bbq-gourmet",
    price: 0,
    category: "cestas-gourmet",
    featured: false,
    description: "Cesta gourmet navideña. Pedidos y precios por mayor.",
    contents: [],
    image: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-bbq-gourmet.png",
    hoverImage: "https://canastanavidena.pe/wp-content/uploads/2026/07/regalo-navideno-bbq-gourmet.png",
  },
];

export const getProductBySlug = (slug) => PRODUCTS.find((p) => p.slug === slug);

export const CATEGORIES = [
  { id: "todos", label: "Todas" },
  { id: "ejecutivas", label: "Ejecutivas" },
  { id: "exclusivas", label: "Exclusivas" },
  { id: "familiares", label: "Familiares" },
  { id: "corporativas", label: "Corporativas" },
  { id: "regalos-navidenos", label: "Regalos Navideños" },
  { id: "cestas-gourmet", label: "Cestas Gourmet" },
];

export const CATEGORIES_FULL = [
  {
    id: "ejecutivas",
    label: "Ejecutivas",
    slug: "ejecutivas",
    description: "Canastas navideñas ejecutivas para empresas.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-3-3.jpg",
    metaTitle: "Canastas Navideñas Ejecutivas | Publiventa",
    metaDescription: "Canastas navideñas ejecutivas para empresas.",
  },
  {
    id: "exclusivas",
    label: "Exclusivas",
    slug: "exclusivas",
    description: "Canastas navideñas exclusivas con los mejores productos.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-5.jpg",
    metaTitle: "Canastas Navideñas Exclusivas | Publiventa",
    metaDescription: "Canastas navideñas exclusivas con productos gourmet.",
  },
  {
    id: "familiares",
    label: "Familiares",
    slug: "familiares",
    description: "Canastas textiles y de plástico para toda ocasión.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-4.jpg",
    metaTitle: "Canastas Familiares | Publiventa",
    metaDescription: "Canastas textiles y de plástico.",
  },
  {
    id: "corporativas",
    label: "Corporativas",
    slug: "corporativas",
    description: "Canastas navideñas corporativas para empresas.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-6-10.jpg",
    metaTitle: "Canastas Navideñas Corporativas | Publiventa",
    metaDescription: "Canastas navideñas corporativas para empresas.",
  },
  {
    id: "regalos-navidenos",
    label: "Regalos Navideños",
    slug: "regalos-navidenos",
    description: "Regalos navideños para toda ocasión.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-6.jpg",
    metaTitle: "Regalos Navideños | Publiventa",
    metaDescription: "Regalos navideños para toda ocasión.",
  },
  {
    id: "cestas-gourmet",
    label: "Cestas Gourmet",
    slug: "cestas-gourmet",
    description: "Cestas gourmet con productos selectos.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-7-3.jpg",
    metaTitle: "Cestas Gourmet | Publiventa",
    metaDescription: "Cestas gourmet con productos selectos.",
  },
];

export const CLIENTS = [
  { name: "Stracon", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Stracon-1.png" },
  { name: "Caja Arequipa", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Caja-Arequipa.png" },
  { name: "Ochosur", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Ochosur.png" },
  { name: "Kori", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Kori.png" },
  { name: "Arcos Dorados", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Arcos-Dorados.png" },
  { name: "Pardos Chicken", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Pardos-Chicken.png" },
  { name: "SENTAI", logo: "https://publiventa.pe/wp-content/uploads/2025/08/LOGO_SENTAI-e1755279214511.png" },
  { name: "Refinca", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Refinca.png" },
  { name: "CBC", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Cbc.png" },
  { name: "Cana Brava", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Cana-Brava.png" },
  { name: "AC Laboratorios", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Ac-Laboratorios.png" },
  { name: "Peru", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Peru.png" },
  { name: "Control Union", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Controlunion.png" },
  { name: "Group 766", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Group-766.png" },
  { name: "Etex", logo: "https://publiventa.pe/wp-content/uploads/2026/07/Etex.png" },
];
