export const PRODUCTS = [
  // ==================== EJECUTIVAS ====================
  {
    id: 1,
    name: "Canasta Navideña Allin",
    slug: "canasta-navidena-allin",
    price: 50,
    category: "ejecutivas",
    featured: true,
    description: "Presentación: Contenedor caja | Cortesía: Tarjeta de saludo.",
    contents: ["Panetón tradicional 750g", "HR familiar 750g", "Azúcar rubia Dulfina 1/2 kg", "Aceite Doña Gumi 900ml", "Tableta chocolate Cusco Andino 80g", "Ideal amanecer 390g", "Marco Polo spaghetti 450g", "Grated de atún 140g", "Avena grano de oro 80g", "Té canela y clavo"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-3-3.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-3-3.jpg",
  },
  {
    id: 2,
    name: "Canasta Navideña Kantu",
    slug: "canasta-navidena-kantu",
    price: 30,
    category: "ejecutivas",
    featured: true,
    description: "Presentación: Bolsa notex | Cortesía: Tarjeta de saludo.",
    contents: ["Panetón PYC bolsa 800g", "HR familiar 750g", "Azúcar rubia Dulfina 1/2 kg", "Tableta chocolate Cusco Andino 80g", "Ideal amanecer 390g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-1-3.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-1-3.jpg",
  },
  {
    id: 3,
    name: "Canasta Navideña Allinmunay",
    slug: "canasta-navidena-allinmunay",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña con variedad de productos. Pedidos y precios por mayor.",
    contents: ["D'onofrio panetón 880g", "Espumante Tabernero rosé 750ml", "Tableta chocolate Cusco Andino 80g", "Ideal amanecer 390g", "Azúcar rubia Dulfina 1/2 kg", "Avena clásica 110g", "HR familiar 750g", "Compass duraznos 410g", "Fanny deli fresa 75g", "Marco Polo tornillo 235g", "Wafer chocolate 105g", "Lenteja bebe 500g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-6.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-6.jpg",
  },
  {
    id: 4,
    name: "Canasta Navideña Suma",
    slug: "canasta-navidena-suma",
    price: 30,
    category: "ejecutivas",
    featured: true,
    description: "Presentación: Contenedor caja | Cortesía: Tarjeta de saludo.",
    contents: ["Panetón tradicional 750g", "HR familiar 750g", "Azúcar rubia Dulfina 1/2 kg", "Tableta chocolate Cusco Andino 80g", "Ideal amanecer 390g", "Té canela y clavo", "Avena grano de oro 80g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-2-3.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-2-3.jpg",
  },
  {
    id: 5,
    name: "Canasta Navideña Kawsay",
    slug: "canasta-navidena-kawsay",
    price: 0,
    category: "ejecutivas",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["Gloria panetón 900g", "Azúcar La Bodeguita", "Fideos La Bodeguita", "Galletas Colombina", "Arroz Costeño 750g", "Leche Ideal Amanecer", "Grated atún", "Tableta chocolate Cusco Andino 80g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-9-4.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-9-4.jpg",
  },

  // ==================== EXCLUSIVAS ====================
  {
    id: 6,
    name: "Canasta Navideña Munay",
    slug: "canasta-navidena-munay",
    price: 99.99,
    category: "exclusivas",
    featured: true,
    description: "Presentación: Caja plástico baúl MAGICPLAST 40 Ltrs | Cortesía: Tarjeta de saludo.",
    contents: ["Panetón PYC bolsa 800g", "Espumante Tabernero rosé 750ml", "HR familiar 750g", "Azúcar rubia Dulfina 1/2 kg", "Aceite Doña Gumi 900ml", "Tableta chocolate Cusco Andino 80g", "Ideal amanecer 390g", "Marco Polo spaghetti 450g", "Grated de atún 140g", "Avena grano de oro 80g", "Compass duraznos 410g", "Wafer chocolate 105g", "Fanny deli fresa 75g", "Semola grano de oro 200g", "Sal de cocina 1 kg", "Compass vinagre 125ml", "Berry Mix ValleAlto 40g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-8-2.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-8-2.jpg",
  },
  {
    id: 7,
    name: "Canasta Navideña Hatun",
    slug: "canasta-navidena-hatun",
    price: 245.50,
    category: "exclusivas",
    featured: true,
    description: "Presentación: Maletín deportivo | Cortesía: Tarjeta de saludo.",
    contents: ["D'onofrio panetón caja 880g", "Espumante Tabernero rosé 750ml", "HR familiar 750g", "Azúcar rubia Dulfina 1/2 kg", "Aceite Doña Gumi 900ml", "Tableta chocolate Cusco Andino 80g", "Ideal amanecer 390g", "Marco Polo spaghetti 450g", "Grated de atún 140g", "Avena grano de oro 80g", "Compass duraznos 410g", "Wafer chocolate 105g", "Fanny deli fresa 75g", "Semola grano de oro 200g", "Sal de cocina 1 kg", "Compass vinagre 125ml", "Berry Mix ValleAlto 40g", "Gloria leche condensada 200g", "Café Doña Gumi 25g", "Gloria beb durazno 1L", "Gelatina Doña Gumi fresa 150g", "Marco Polo tornillo 235g", "HR frijol canario 500g", "HR arveja verde 500g", "Choc. taza real Winters 90g", "Bolsa feliz Navidad Colombina 220g", "Pringles original 104g", "Mayonesa Alacena 95g", "Gloria mantequilla 180g", "Pomarola salsa clásica 145g", "Universal flan 150g", "Gaseosa Inca Kola 1.5L", "Milo activ-go 190g", "Marco Polo macarrón 235g", "Marco Polo tornillo 235g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-6-10.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-6-10.jpg",
  },
  {
    id: 8,
    name: "Canasta Navideña Qori",
    slug: "canasta-navidena-qori",
    price: 109.99,
    category: "exclusivas",
    featured: false,
    description: "Presentación: Contenedor caja mediana | Cortesía: Tarjeta de saludo.",
    contents: ["Panetón PYC bolsa 800g", "HR familiar 750g", "Azúcar rubia Dulfina 1/2 kg", "Aceite Doña Gumi 900ml", "Tableta chocolate Cusco Andino 80g", "Ideal amanecer 390g", "Marco Polo spaghetti 450g", "Grated de atún 140g", "Avena grano de oro 80g", "Compass duraznos 410g", "Wafer chocolate 105g", "Fanny deli fresa 75g", "Semola grano de oro 200g", "Sal de cocina 1 kg", "Compass vinagre 125ml", "Arveja verde 500g", "Lentejita marrón 500g", "Frijol castilla 500g", "Berry Mix ValleAlto 40g", "Gloria leche condensada 200g", "Café Doña Gumi 25g", "Gloria beb durazno 1L", "Gelatina Doña Gumi fresa 150g", "Marco Polo munición 250g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-7-3.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-7-3.jpg",
  },
  {
    id: 9,
    name: "Canasta Navideña Sumaq",
    slug: "canasta-navidena-sumaq",
    price: 0,
    category: "exclusivas",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["Florida filete atún 140g", "Hershey tab 40% m/amargo 82g", "Hershey's tab chocolate c/almendra", "Bauducco panetone 900g", "Pringles original 104g", "Florida aceite de maíz 900ml", "Chocolate a la taza 100% cacao 100g", "Costeño arveja verde 500g", "Paisana lenteja 500g", "Costeño frijol canario 500g", "Costeño frijol panamito 500g", "Paisana superior 5 kg", "Costeño azúcar rubia 2 kg", "Fanny duraznos 820g", "Fanny deli fresa barril 950g", "Mc Collins inf. manzanilla 25u", "Mc Collins inf. té canela clavo 25u", "Mayonesa Alacena 95g", "Molitalia pasta tornillo 235g", "Don Vittorio canuto chico 235g", "Avena Quaker tradicional 500g", "Costa bizcocho mini chocman 12x20g", "Costa galletas chocodonuts 135g", "Universal gelatina 130g fresa", "Altomayo café inst. gourmet 90g", "Nestlé leche condensada 393g", "Gloria leche rec. entera 390g", "Granuts kraks oriental 180g", "Marshmallow Mellows Ambrosoli 230g", "ValleAlto berry mix 40g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-4-11.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-4-11.jpg",
  },
  {
    id: 10,
    name: "Canasta Navideña Taki",
    slug: "canasta-navidena-taki",
    price: 0,
    category: "exclusivas",
    featured: false,
    description: "Canasta navideña con variedad de productos. Pedidos y precios por mayor.",
    contents: ["Panetón personalizado 900g", "Mini panetón caja 80g", "Ecco bebida base cebada 170g", "Cocoa Doña Gumi 160g", "Casa Grande azúcar rubia 2 kg", "Universal gelatina 130g fresa", "Infusión Doña Gumi manzanilla 25u", "Leche sin lactosa Laive chocolate 1L", "Atún en trozos en aceite 170g", "Galletas de arroz Costeño pimienta", "Dip de pimiento", "Ají criollo Walibi 200g", "Huancaina Walibi 200g", "Bebida Watts de durazno 1L", "Fanny mermelada pote 320g", "Bizcocho chocman sixpack 14x6x28g", "Granuts chocolate almendra 120g", "Gomas frugele XL 12g", "Gran cereal clásica 36g", "Papas Kryzpo Sam original 37g", "Ideal amanecer 395g", "Ph noble DH 2x10 pack"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-10-7.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-10-7.jpg",
  },

  // ==================== FAMILIARES ====================
  {
    id: 11,
    name: "Canastas textiles",
    slug: "canastas-textiles",
    price: 0,
    category: "familiares",
    featured: true,
    description: "Canastas tejidas en telas y fibras naturales, ideales para regalos corporativos.",
    contents: [],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-4.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-4.jpg",
  },
  {
    id: 12,
    name: "Canastas de plástico",
    slug: "canastas-de-plastico",
    price: 0,
    category: "familiares",
    featured: true,
    description: "Canastas resistentes y versátiles fabricadas en plástico de alta calidad.",
    contents: [],
    image: "https://publiventa.pe/wp-content/uploads/2017/10/canasta10.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2017/10/canasta10.jpg",
  },

  // ==================== CORPORATIVAS ====================
  {
    id: 13,
    name: "Canasta Navideña Tinkuy",
    slug: "canasta-navidena-tinkuy",
    price: 0,
    category: "corporativas",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["D'onofrio panetón caja 880g", "Gloria mantequilla 180g", "Florida filete atún 140g", "Gelatina universal 160g", "Mazamorra universal 150g", "Gloria leche rec. entera 390g", "Compass mermelada fresa 310g", "Pomarola salsa clásica 145g", "Avena premium 3 ositos 900g", "Caja filtrante Mc Collins 100u", "Winter cocoa doypack 150g", "Mayonesa Alacena 190g", "Nestlé leche condensada 393g", "Pallar 500g", "Chocman sixpack"],
    image: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas2.png",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas2.png",
  },
  {
    id: 14,
    name: "Canasta Navideña Wasiykuy",
    slug: "canasta-navidena-wasiykuy",
    price: 0,
    category: "corporativas",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["D'onofrio panetón caja 880g", "Espumante Riccadonna Asti 750ml", "Gloria leche rec. entera 390g", "Chocolate a la taza con azúcar 46% cacao 100g", "Bolsa feliz Navidad galleta Colombina 220g", "Puré de manzana y mango", "Pasta ensalada tornillo 235g", "Toffees surtidos 100g", "Duraznos mitades 820g", "Aceite de oliva virgen 200ml", "Costeño superior 750g", "Azúcar rubia 1 kg", "Mermelada de arándano con mango", "Dip con palta", "Estuche de barquillos Antiu Xixona 75g"],
    image: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas12.png",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas12.png",
  },
  {
    id: 15,
    name: "Canasta Navideña Sullpayki",
    slug: "canasta-navidena-sullpayki",
    price: 0,
    category: "corporativas",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["Panetón 900g caja personalizada", "Aceite vegetal SAO 900ml", "HR familiar 750g", "Sta. Catalina avena 500g", "Arica duraznos 820g", "Marco Polo spaghetti 450g", "Arveja verde Kimolin 500g", "Fanny mermelada pote 320g", "Gelatina Doña Gumi fresa 150g", "Lenteja Komilon 500g", "Azúcar Doña Gumi rubia 500g", "Tableta chocolate Cusco Andino 80g", "Gloria beb durazno 1L", "Gloria leche rec. entera 390g", "Atún trozos aceite Compass 170g", "Toffes Oet surtido 100g"],
    image: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas9.png",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas9.png",
  },

  // ==================== CESTAS GOURMET ====================
  {
    id: 16,
    name: "Canasta Navideña Sani",
    slug: "canasta-navidena-sani",
    price: 289.99,
    category: "cestas-gourmet",
    featured: true,
    description: "Presentación: Carry on | Cortesía: Tarjeta de saludo.",
    contents: ["D'onofrio panetón caja 880g", "Espumante Tabernero rosé 750ml", "HR familiar 750g", "Azúcar rubia Dulfina 1/2 kg", "Aceite Doña Gumi 900ml", "Tableta chocolate Cusco Andino 80g", "Ideal amanecer 390g", "Marco Polo spaghetti 450g", "Grated de atún 140g", "Avena grano de oro 80g", "Compass duraznos 410g", "Wafer chocolate 105g", "Fanny deli fresa 75g", "Semola grano de oro 200g", "Sal de cocina 1 kg", "Compass vinagre 125ml", "Berry Mix ValleAlto 40g", "Gloria leche condensada 200g", "Café Doña Gumi 25g", "Gloria beb durazno 1L", "Gelatina Doña Gumi fresa 150g", "Molitalia cabello ángel 250g", "HR frijol canario 500g", "HR arveja verde 500g", "Choc. taza real Winters 90g", "Bolsa feliz Navidad Colombina 220g", "Pringles original 104g", "Mayonesa Alacena 95g", "Gloria mantequilla 180g", "Pomarola salsa clásica 145g", "Universal flan 150g", "Gaseosa Inca Kola 1.5L", "Milo activ-go 190g", "Marco Polo macarrón 235g", "Marco Polo tornillo 235g", "Costa vizzio estuche 122g", "Harina sin preparar 180g", "Universal mazamorra 150g", "Manjar Laive doypack 200g", "Gloria yogur desc. fresa 1kg", "Molitalia mezcla keke vainilla 450g", "Froot Loops 75g", "Ají pollero", "Salsa blanca 370ml"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-5-2.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-5-2.jpg",
  },
  {
    id: 17,
    name: "Canasta Navideña Pukllay",
    slug: "canasta-navidena-pukllay",
    price: 0,
    category: "cestas-gourmet",
    featured: true,
    description: "Canasta navideña premium con productos selectos de alta calidad.",
    contents: ["Panetón Blanca Flor 900g", "Champ. Riccadonna ruby 750ml", "Costeño superior 750g", "Azúcar rubia Dulfina 1 kg", "Aceite Costeño 900ml", "Tableta Cusco Real trad. 80g", "Ideal amanecer 390g", "Fanny mermelada pote 320g", "Molitalia spaghetti 450g", "Florida filete de atún 140g", "Lenteja bebe Valenorte 500g", "Altomayo café instantáneo gourmet 45g", "Duraznos mitades 820g Arica", "Universal gelatina 130g fresa", "Gomas Ambrosia 90g"],
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-5.jpg",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-5.jpg",
  },
  {
    id: 18,
    name: "Canasta Navideña Qapaq",
    slug: "canasta-navidena-qapaq",
    price: 0,
    category: "cestas-gourmet",
    featured: false,
    description: "Canasta navideña con productos selectos. Pedidos y precios por mayor.",
    contents: ["Florida filete atún 140g", "Hershey tab 40% m/amargo 82g", "Hershey's tab chocolate c/almendra", "Bauducco panetone 900g", "Pringles original 104g", "Florida aceite de maíz 900ml", "Chocolate a la taza 100% cacao 100g", "Costeño arveja verde 500g", "Paisana lenteja 500g", "Costeño frijol canario 500g", "Costeño frijol panamito 500g", "Paisana superior 5 kg", "Costeño azúcar rubia 2 kg", "Fanny duraznos 820g", "Fanny deli fresa barril 950g", "Mc Collins inf. manzanilla 25u", "Mc Collins inf. té canela clavo 25u", "Casa verde dip con palta", "Casa verde dip de espárrago", "Mayonesa Alacena 95g", "Molitalia pasta tornillo 235g", "Don Vittorio spaghetti 450g", "Don Vittorio canuto chico 235g", "Avena Quaker tradicional 500g", "Costa bizcocho mini chocman 12x20g", "Costa galletas chocodonuts 135g", "Universal gelatina 130g fresa", "Altomayo café inst. gourmet 90g", "Nestlé leche condensada 393g", "Gloria leche rec. entera 390g", "Granuts kraks oriental 180g", "Marshmallow Mellows Ambrosoli 230g", "ValleAlto berry mix 40g"],
    image: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas11.png",
    hoverImage: "https://publiventa.pe/wp-content/uploads/2024/09/Canastas-Navidenas11.png",
  },
];

export const getProductBySlug = (slug) => PRODUCTS.find((p) => p.slug === slug);

export const CATEGORIES = [
  { id: "todos", label: "Todas" },
  { id: "ejecutivas", label: "Ejecutivas" },
  { id: "exclusivas", label: "Exclusivas" },
  { id: "familiares", label: "Familiares" },
  { id: "corporativas", label: "Corporativas" },
  { id: "regalos-navidenos", label: "Regalos Navideños" },
  { id: "cestas-gourmet", label: "Cestas Gourmet" },
];

export const CATEGORIES_FULL = [
  {
    id: "ejecutivas",
    label: "Ejecutivas",
    slug: "ejecutivas",
    description: "Canastas navideñas ejecutivas para empresas.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-3-3.jpg",
    metaTitle: "Canastas Navideñas Ejecutivas | Publiventa",
    metaDescription: "Canastas navideñas ejecutivas para empresas.",
  },
  {
    id: "exclusivas",
    label: "Exclusivas",
    slug: "exclusivas",
    description: "Canastas navideñas exclusivas con los mejores productos.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-5.jpg",
    metaTitle: "Canastas Navideñas Exclusivas | Publiventa",
    metaDescription: "Canastas navideñas exclusivas con productos gourmet.",
  },
  {
    id: "familiares",
    label: "Familiares",
    slug: "familiares",
    description: "Canastas textiles y de plástico para toda ocasión.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-4.jpg",
    metaTitle: "Canastas Familiares | Publiventa",
    metaDescription: "Canastas textiles y de plástico.",
  },
  {
    id: "corporativas",
    label: "Corporativas",
    slug: "corporativas",
    description: "Canastas navideñas corporativas para empresas.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-6-10.jpg",
    metaTitle: "Canastas Navideñas Corporativas | Publiventa",
    metaDescription: "Canastas navideñas corporativas para empresas.",
  },
  {
    id: "regalos-navidenos",
    label: "Regalos Navideños",
    slug: "regalos-navidenos",
    description: "Regalos navideños para toda ocasión.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-6.jpg",
    metaTitle: "Regalos Navideños | Publiventa",
    metaDescription: "Regalos navideños para toda ocasión.",
  },
  {
    id: "cestas-gourmet",
    label: "Cestas Gourmet",
    slug: "cestas-gourmet",
    description: "Cestas gourmet con productos selectos.",
    image: "https://publiventa.pe/wp-content/uploads/2025/09/Mesa-de-trabajo-7-3.jpg",
    metaTitle: "Cestas Gourmet | Publiventa",
    metaDescription: "Cestas gourmet con productos selectos.",
  },
];

export const CLIENTS = [
  { name: "LOGOS-CLIENTES-10", logo: "https://publiventa.pe/wp-content/uploads/2025/07/LOGOS-CLIENTES-10-e1753974079926.png" },
  { name: "LOGOS-CLIENTES-08", logo: "https://publiventa.pe/wp-content/uploads/2025/07/LOGOS-CLIENTES-08-e1753975783493.png" },
  { name: "LOGOS-CLIENTES-11", logo: "https://publiventa.pe/wp-content/uploads/2025/07/LOGOS-CLIENTES-11-e1753975817436.png" },
  { name: "LOGOS-CLIENTES-15", logo: "https://publiventa.pe/wp-content/uploads/2025/07/LOGOS-CLIENTES-15-e1753975592348.png" },
  { name: "LOGOS-CLIENTES-03", logo: "https://publiventa.pe/wp-content/uploads/2025/07/LOGOS-CLIENTES-03-e1753975698141.png" },
  { name: "LOGOS-CLIENTES-12", logo: "https://publiventa.pe/wp-content/uploads/2025/07/LOGOS-CLIENTES-12-e1753975527689.png" },
  { name: "LOGOS-CLIENTES-04", logo: "https://publiventa.pe/wp-content/uploads/2025/07/LOGOS-CLIENTES-04-e1753974768260.png" },
  { name: "SENTAI", logo: "https://publiventa.pe/wp-content/uploads/2025/08/LOGO_SENTAI-e1755279214511.png" },
];
