-- ============================================================
-- Seed: Categories
-- ============================================================

INSERT INTO ecomm_categories (id, slug, label, description, image_url, meta_title, meta_description, sort_order) VALUES
('corporativas', 'corporativas', 'Canastas Corporativas', 'Canastas navideñas corporativas diseñadas para empresas que buscan impresionar a clientes, colaboradores y socios de negocios con regalos gourmet de alto nivel.', '/images/optimized/corporativas.webp', 'Canastas Navideñas Corporativas | Regalos Empresariales de Navidad', 'Descubre nuestras canastas navideñas corporativas. Regalos empresariales premium con vinos, quesos, embutidos y chocolates para clientes y colaboradores.', 1),
('familiares', 'familiares', 'Canastas Familiares', 'Canastas navideñas para compartir en familia. Panetones, chocolates, dulces tradicionales y bebidas que alegran las reuniones navideñas más especiales.', '/images/optimized/familiares.webp', 'Canastas Navideñas Familiares | Para Compartir en Navidad', 'Canastas navideñas familiares con panetón, chocolates, dulces y más. Ideales para reuniones familiares y celebrar la Navidad en grande.', 2),
('premium', 'premium', 'Canastas Premium', 'Selección magistral de productos gourmet de la más alta categoría. Vinos de reserva, quesos curados, embutidos importados y chocolate belga para paladares exigentes.', '/images/optimized/premium.webp', 'Canastas Navideñas Premium | Lujo y Calidad Gourmet', 'Canastas navideñas premium con los mejores productos gourmet. Vinos reserva, quesos curados, jamón ibérico y chocolate belga de lujo.', 3),
('economicas', 'economicas', 'Canastas Económicas', 'Canastas navideñas accesibles sin sacrificar calidad. Detalles perfectos para regalar con amor y sin romper el presupuesto durante la temporada navideña.', '/images/optimized/economicas.webp', 'Canastas Navideñas Económicas | Regalos Navideños Baratos', 'Canastas navideñas económicas a precios accesibles. Regalos de Navidad bonitos y originales sin gastar de más.', 4),
('arcones', 'arcones', 'Arcones y Cestas Gourmet', 'Arcones navideños y cestas gourmet con la mayor variedad de productos. Presentaciones espectaculares en cajas de madera o cartón premium para regalar con impacto.', '/images/optimized/arcones.webp', 'Arcones Navideños y Cestas Gourmet | Regalos de Navidad Grandes', 'Arcones navideños y cestas gourmet con variedad de productos premium. Presentaciones de lujo para regalar en Navidad con todo incluido.', 5),
('regalos', 'regalos', 'Regalos de Navidad', 'Regalos navideños originales para toda ocasión. Desde el amigo invisible hasta regalos ejecutivos, tenemos el detalle perfecto para cada persona especial.', '/images/optimized/regalos.webp', 'Regalos Navideños Originales | Ideas para Regalar en Navidad', 'Regalos navideños originales y personalizados. Ideas originales para amigo invisible, jefe, pareja y familia. Envío gratis en Navidad.', 6)
ON CONFLICT (id) DO NOTHING;
